---
- name: Archive messages
  command: "{{ rapidpro_archiver_archive_messages_command }}"
  args:
    chdir: "{{ rapidpro_archiver_active_package_symlink }}"
  when: rapidpro_archiver_archive_messages | bool

- name: Archive runs
  command: "{{ rapidpro_archiver_archive_runs_command }}"
  args:
    chdir: "{{ rapidpro_archiver_active_package_symlink }}"
  when: rapidpro_archiver_archive_runs | bool
